# Generated by Django 4.0.1 on 2022-02-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_bio_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='bio',
            field=models.TextField(blank=True, default='Hi I am {{user.username}}', max_length=500),
        ),
    ]
