# Generated by Django 4.0.1 on 2022-02-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_bio_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
