# Generated by Django 4.0.1 on 2022-02-09 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Fullstack', 'Fullstack'), ('Frontend', 'Frontend'), ('Backend', 'Backend')], default='fullstack', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.ImageField(default='post.jpg', upload_to='profile_pic'),
        ),
    ]
